name: Avi Aryan

markdown: kramdown

fullpath: http://aviaryan.in
description: Avi Aryan's personal website
baseurl: 
permalink: /blog/:categories/:title.html
title: Avi Aryan

highlighter: rouge

gems:
  - jemoji
  - jekyll-mentions

# More
author:
    fullname: Avi Aryan
    twitter: aviaryan123
    github: aviaryan
    facebook: aviaryan123
    google: AviAryan
    gplusid: 110328513842183229282

googleverify: gC8gMLC1UpPDYi2y5KR_9Sq79n4TYMiQM7UcSvtyfms
disqusid: avi-aryan-github
disqusurl: http://aviaryan.in
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
jekyllversion: 3.0.3