name: liuyujia

markdown: kramdown

fullpath: http://aviaryan.in
description: liuyujia's personal website
baseurl: 
permalink: /blog/:categories/:title.html
title: liuyujia

highlighter: rouge

gems:
  - jemoji
  - jekyll-mentions

# More
author:
    fullname: liuyujia
    WeChat: liuyujia_haha
    github: liuyujiahaha
    QQ: 417378336
    googleMail: liuyujiahaha@Gmail.com
    stackoverflow: liuyujia
    # gplusid: 110328513842183229282

googleverify: gC8gMLC1UpPDYi2y5KR_9Sq79n4TYMiQM7UcSvtyfms
# disqusid: avi-aryan-github
disqusurl: https://liuyujiahaha.github.io/
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
jekyllversion: 3.0.3